CC = gcc
CFLAGS = -std=c99
LDFLAGS = -pthread

all: threads_lesson_1 threads_lesson_2

threads_lesson_1: threads_lesson_1.c
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@

threads_lesson_2: threads_lesson_2.c
	$(CC) $(CFLAGS) $(LDFLAGS) $^ -o $@
